"""add approval_actions table

Revision ID: 967dbbfd2a78
Revises: ef8f1c8a91a2
Create Date: 2026-09-06 15:11:16.058239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '967dbbfd2a78'
down_revision: Union[str, None] = 'ef8f1c8a91a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('spend_request_id', sa.UUID(), nullable=False),
    sa.Column('cycle', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('approve', 'approve_different_amount', 'reject', 'request_changes', name='approval_action_type'), nullable=False),
    sa.Column('requested_amount_at_time', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['spend_request_id'], ['spend_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approval_actions')
    # ### end Alembic commands ###
