"""add initiative and spend_request team_members M2M tables

Revision ID: a279aad63df2
Revises: 7c0e18cf5ff4
Create Date: 2026-09-05 11:02:51.962519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a279aad63df2'
down_revision: Union[str, None] = '7c0e18cf5ff4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('initiative_team_members',
    sa.Column('initiative_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('initiative_id', 'user_id')
    )
    op.create_table('spend_request_team_members',
    sa.Column('spend_request_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['spend_request_id'], ['spend_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('spend_request_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spend_request_team_members')
    op.drop_table('initiative_team_members')
    # ### end Alembic commands ###
