"""add initiative budget decision and category fields

Revision ID: e8fb28cdf255
Revises: d3f6b8a1c2e7
Create Date: 2026-09-22 12:56:48.677887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e8fb28cdf255'
down_revision: Union[str, None] = 'd3f6b8a1c2e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('initiatives', sa.Column('category_id', sa.UUID(), nullable=True))
    # add_column doesn't auto-create a Postgres enum type the way create_table
    # does — create it explicitly first, then add the column without letting
    # SQLAlchemy try (and fail) to create it a second time.
    initiative_budget_decision = sa.Enum('approved', 'rejected', name='initiative_budget_decision')
    initiative_budget_decision.create(op.get_bind(), checkfirst=True)
    op.add_column(
        'initiatives',
        sa.Column(
            'budget_decision',
            sa.Enum('approved', 'rejected', name='initiative_budget_decision', create_type=False),
            nullable=True,
        ),
    )
    op.add_column('initiatives', sa.Column('budget_approved_amount', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('initiatives', sa.Column('budget_decided_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('initiatives', sa.Column('budget_decided_by_id', sa.UUID(), nullable=True))
    op.add_column('initiatives', sa.Column('budget_decision_comment', sa.Text(), nullable=True))
    op.create_foreign_key(
        'fk_initiatives_budget_decided_by_id_users', 'initiatives', 'users', ['budget_decided_by_id'], ['id']
    )
    op.create_foreign_key('fk_initiatives_category_id_categories', 'initiatives', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_initiatives_category_id_categories', 'initiatives', type_='foreignkey')
    op.drop_constraint('fk_initiatives_budget_decided_by_id_users', 'initiatives', type_='foreignkey')
    op.drop_column('initiatives', 'budget_decision_comment')
    op.drop_column('initiatives', 'budget_decided_by_id')
    op.drop_column('initiatives', 'budget_decided_at')
    op.drop_column('initiatives', 'budget_approved_amount')
    op.drop_column('initiatives', 'budget_decision')
    sa.Enum(name='initiative_budget_decision').drop(op.get_bind(), checkfirst=True)
    op.drop_column('initiatives', 'category_id')
    # ### end Alembic commands ###
