"""expand initiative and spend request fields, add line items and dynamic field schema

Revision ID: ef47cbb3e1bb
Revises: a279aad63df2
Create Date: 2026-09-05 14:23:20.048455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ef47cbb3e1bb'
down_revision: Union[str, None] = 'a279aad63df2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spend_request_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('spend_request_id', sa.UUID(), nullable=False),
    sa.Column('item', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['spend_request_id'], ['spend_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('initiatives', sa.Column('business_unit', sa.String(), nullable=True))
    op.add_column('initiatives', sa.Column('region', sa.String(), nullable=True))
    op.add_column('initiatives', sa.Column('target_audience', sa.Text(), nullable=True))
    op.add_column('initiatives', sa.Column('objective', sa.Text(), nullable=True))
    op.add_column('initiatives', sa.Column('estimated_total_budget', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('initiatives', sa.Column('client_prospect', sa.String(), nullable=True))
    op.add_column('initiatives', sa.Column('strategic_account', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('initiatives', sa.Column('campaign_program', sa.String(), nullable=True))
    op.add_column('initiatives', sa.Column('expected_leads_meetings', sa.Text(), nullable=True))
    op.add_column('spend_requests', sa.Column('business_unit', sa.String(), nullable=True))
    op.add_column('spend_requests', sa.Column('region', sa.String(), nullable=True))
    op.add_column('spend_requests', sa.Column('client_prospect', sa.String(), nullable=True))
    op.add_column('spend_requests', sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('spend_requests', sa.Column('has_existing_po', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('spend_requests', sa.Column('po_number', sa.String(), nullable=True))
    op.add_column('spend_requests', sa.Column('vendor_quotation_amount', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('spend_requests', sa.Column('dynamic_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('subcategories', sa.Column('dynamic_field_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subcategories', 'dynamic_field_schema')
    op.drop_column('spend_requests', 'dynamic_answers')
    op.drop_column('spend_requests', 'vendor_quotation_amount')
    op.drop_column('spend_requests', 'po_number')
    op.drop_column('spend_requests', 'has_existing_po')
    op.drop_column('spend_requests', 'tax_amount')
    op.drop_column('spend_requests', 'client_prospect')
    op.drop_column('spend_requests', 'region')
    op.drop_column('spend_requests', 'business_unit')
    op.drop_column('initiatives', 'expected_leads_meetings')
    op.drop_column('initiatives', 'campaign_program')
    op.drop_column('initiatives', 'strategic_account')
    op.drop_column('initiatives', 'client_prospect')
    op.drop_column('initiatives', 'estimated_total_budget')
    op.drop_column('initiatives', 'objective')
    op.drop_column('initiatives', 'target_audience')
    op.drop_column('initiatives', 'region')
    op.drop_column('initiatives', 'business_unit')
    op.drop_table('spend_request_line_items')
    # ### end Alembic commands ###
